---
title: "Case-control matching"
author: "Sophie Meakin"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
date: "`r format(Sys.Date(), '%d %B %Y')`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  include = TRUE, cache = FALSE, echo = FALSE,
  tidy = TRUE,
  warning = FALSE, message = FALSE, error = FALSE,
  fig.show = 'hold',
  fig.width = 12,
  fig.height = 9, 
  dpi = 300,
  dev = 'png'
)
```

```{r}
library(here)
library(magrittr)
library(dplyr)
library(tidyr)
library(tibble)
library(gtsummary)
library(ggplot2)
```

```{r}
source(here("R/set_paths.R"))
paths <- set_paths()
path_matched_data <- here("outputs", "matched_data")

source(here("R/matching.R"))
```

```{r}
paired_pal <- RColorBrewer::brewer.pal(name = "Paired", n = 6)
cols <- c(
  "case" = paired_pal[6],
  "case_unmatch" = paired_pal[5],
  "control" = paired_pal[2],
  "control_unmatch" = paired_pal[1]
)
custom_pal <- scale_fill_manual(values = cols)
```


# Load data

```{r}
# Unmatched
etc_10d_unmatched <- readRDS(file = here("outputs", "matched_data", "imp_m10_unmatched_10d.rds"))
# Matched
data_a1 <- readRDS(file = here("outputs", "matched_data", "imp_m10_matched_n10_10d_a1.rds"))
```

# Matching demographics {.tabset}

-   Imputed data
-   EVD exposure: contact with an EVD case

```{r}
# Get number of cases/controls matched/unmatched by matching strata
strata_a1 <- get_matching_vals(
  etc_10d_unmatched %>%
    filter(contact_evd_case == "Yes") %>%
    filter(.imp == 3 | is.na(.imp))
  ) %>%
  rename(
    adm2 = adm2_name__res,
    month = month_onset
    ) %>%
  mutate(
    month = as.Date(paste0(month, "-01"))
  )
```

## Figures

### Figure: By onset month and health zone
```{r}
# Distribution of matched/unmatched cases/controls by month and HZ
strata_a1  %>%
  group_by(adm2, month, name) %>%
  summarise(value = sum(value, na.rm = TRUE),
            .groups = "drop") %>%
  group_by(adm2) %>%
  mutate(n_case = sum(value[which(grepl("case", name))])) %>%
  filter(n_case > 0) %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_wrap(~ adm2, scales = "free_y") +
  scale_x_date(breaks = "4 months", date_labels = "%b%y") +
  scale_y_continuous(breaks = scales::pretty_breaks(min.n = 0)) +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "") +
  theme_bw() +
  theme(legend.position = "top")
```

### Figure: By all matching variables
```{r}
# Beni
g_beni_tot <- strata_a1  %>%
  filter(adm2 %in% c("Beni")) %>%
  group_by(adm2, month, name) %>%
  summarise(value = sum(value, na.rm = TRUE),
            .groups = "drop") %>%
  group_by(adm2) %>%
  mutate(n_case = sum(value[which(name == "case")])) %>%
  filter(n_case > 0) %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_wrap(~ adm2, ncol = 1, scales = "free_y") +
  scale_x_date(breaks = "2 months", date_labels = "%b%y") +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "",
       subtitle = "A") +
  theme_bw() +
  theme(legend.position = "top")

g_beni_sexage <- strata_a1 %>%
  filter(adm2 == "Beni") %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_grid(sex ~ age_gp) +
  scale_x_date(breaks = "4 months", date_labels = "%b") +
  scale_y_continuous(breaks = seq(0, 100, 8)) +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "") +
  theme_bw() +
  theme(legend.position = "none")

# Katwa
g_katwa_tot <- strata_a1  %>%
  filter(adm2 %in% c("Katwa")) %>%
  group_by(adm2, month, name) %>%
  summarise(value = sum(value, na.rm = TRUE),
            .groups = "drop") %>%
  group_by(adm2) %>%
  mutate(n_case = sum(value[which(name == "case")])) %>%
  filter(n_case > 0) %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_wrap(~ adm2, ncol = 1, scales = "free_y") +
  scale_x_date(breaks = "2 months", date_labels = "%b%y") +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "",
       subtitle = "B") +
  theme_bw() +
  theme(legend.position = "top")

g_katwa_sexage <- strata_a1 %>%
  filter(adm2 == "Katwa") %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_grid(sex ~ age_gp) +
  scale_x_date(breaks = "4 months", date_labels = "%b") +
  scale_y_continuous(breaks = seq(0, 60, 4)) +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "") +
  theme_bw() +
  theme(legend.position = "none")

# Butembo
g_butembo_tot <- strata_a1  %>%
  filter(adm2 %in% c("Butembo")) %>%
  group_by(adm2, month, name) %>%
  summarise(value = sum(value, na.rm = TRUE),
            .groups = "drop") %>%
  group_by(adm2) %>%
  mutate(n_case = sum(value[which(name == "case")])) %>%
  filter(n_case > 0) %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_wrap(~ adm2, ncol = 1, scales = "free_y") +
  scale_x_date(breaks = "2 months", date_labels = "%b%y") +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "",
       subtitle = "X") +
  theme_bw() +
  theme(legend.position = "top")

g_butembo_sexage <- strata_a1 %>%
  filter(adm2 == "Butembo") %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_grid(sex ~ age_gp) +
  scale_x_date(breaks = "4 months", date_labels = "%b") +
  scale_y_continuous(breaks = seq(0, 60, 4)) +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "") +
  theme_bw() +
  theme(legend.position = "none")

# Mabalako
g_mabalako_tot <- strata_a1  %>%
  filter(adm2 %in% c("Mabalako")) %>%
  group_by(adm2, month, name) %>%
  summarise(value = sum(value, na.rm = TRUE),
            .groups = "drop") %>%
  group_by(adm2) %>%
  mutate(n_case = sum(value[which(name == "case")])) %>%
  filter(n_case > 0) %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_wrap(~ adm2, ncol = 1, scales = "free_y") +
  scale_x_date(breaks = "2 months", date_labels = "%b%y") +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "",
       subtitle = "C") +
  theme_bw() +
  theme(legend.position = "top")

g_mabalako_sexage <- strata_a1 %>%
  filter(adm2 == "Mabalako") %>%
  ggplot(aes(x = month, y = value, fill = name)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  facet_grid(sex ~ age_gp) +
  scale_x_date(breaks = "4 months", date_labels = "%b") +
  scale_y_continuous(breaks = seq(0, 60, 4)) +
  custom_pal +
  labs(x = "Month", y = "count",
       fill = "") +
  theme_bw() +
  theme(legend.position = "none")

# Beni ZS
guide_area() / (g_beni_tot + g_beni_sexage) + plot_layout(guides = "collect", widths = c(1, 5), heights = c(1, 10))

# Katwa ZS
guide_area() / (g_katwa_tot + g_katwa_sexage) + plot_layout(guides = "collect", widths = c(1, 3), heights = c(1, 10))
guide_area() / (g_butembo_tot + g_butembo_sexage) + plot_layout(guides = "collect", widths = c(1, 3), heights = c(1, 10))

# Mabalako ZS
guide_area() / (g_mabalako_tot + g_mabalako_sexage) + plot_layout(guides = "collect", widths = c(1, 3), heights = c(1, 10))

# All (!)
guide_area() / 
  (g_beni_tot + g_beni_sexage) /
  (g_katwa_tot + g_katwa_sexage) /
  (g_mabalako_tot + g_mabalako_sexage) +
   plot_layout(guides = "collect", widths = c(1, 3), heights = c(1, 5, 5, 5))
```

## Tables

Proportion of cases that are matched, by:

-   Overall
-   Sex
-   Age group
-   Calendar month of symptom onset
-   Health zone

```{r}
# Overall
strata_a1 %>%
  filter(grepl("case", name)) %>%
  group_by(name) %>%
  summarise(
    value = sum(value),
    .groups = "drop"
  ) %>%
  pivot_wider() %>%
  mutate(
    p = case / (case + case_unmatch)
    )

# Sex
strata_a1 %>%
  filter(grepl("case", name)) %>%
  group_by(sex, name) %>%
  summarise(
    value = sum(value),
    .groups = "drop"
  ) %>%
  pivot_wider() %>%
  mutate(
    p = case / (case + case_unmatch)
    )

# Age group
strata_a1 %>%
  filter(grepl("case", name)) %>%
  group_by(age_gp, name) %>%
  summarise(
    value = sum(value),
    .groups = "drop"
  ) %>%
  pivot_wider() %>%
  mutate(
    p = case / (case + case_unmatch)
    )

# Month
strata_a1 %>%
  filter(grepl("case", name)) %>%
  group_by(month, name) %>%
  summarise(
    value = sum(value),
    .groups = "drop"
  ) %>%
  pivot_wider() %>%
  mutate(
    p = case / (case + case_unmatch)
    )

# HZ
strata_a1 %>%
  filter(grepl("case", name)) %>%
  group_by(adm2, name) %>%
  summarise(
    value = sum(value),
    .groups = "drop"
  ) %>%
  pivot_wider() %>%
  filter(case > 0) %>%
  mutate(
    p = case / (case + case_unmatch)
    ) %>%
  arrange(-case)
```


# Supplementary: Choosing the case:control ratio

```{r}
# Matched cases and total matched, vs. ratio r
purrr::map_df(.x = 1:4,
              .f = ~ get_match_counts(df = etc_10d_unmatched %>% filter(.imp == 1 | is.na(.imp)),
                                      r = 1:5, date_threshold = "2019-11-30",
                                      exposure_def = .x)
              ) %>%
  mutate(exposure_def = as.character(exposure_def)) %>%
  ggplot(aes(x = case, y = total, col = exposure_def)) +
  geom_line(alpha = 0.5) +
  geom_point(aes(size = r)) +
  scale_x_continuous(limits = c(0, NA)) +
  scale_y_continuous(limits = c(0, NA)) +
  scale_color_brewer(palette = "Set2") +
  scale_size_continuous(range = c(2, 6)) +
  labs(x = "Matched cases", y = "Total matched (cases and controls)",
       title = "Ratio vs. matched cases and total matched",
       size = "Controls\nper case",
       col = "Exposure\ndefinition") +
  theme_bw() +
  theme(legend.position = "top")
```
